### PR TITLE
Retry after encountering a recoverable error when reading.

### PR DESCRIPTION
**Pull request by bschmeck**
Fixes d11wtq/dockerpty#32.

### CODE REVIEW

**Comment by michaelstandley** [comment]
Can this be merged? I have applied this patch to our CI farm as a hot-fix and it has completely resolved this issue: https://github.com/d11wtq/dockerpty/issues/26

**Comment by dnephin** [comment]
LGTM

**Comment by aanand** [comment]
LGTM

**Comment by aanand** [comment]
Thanks very much. We should get this into Compose ASAP to see if it fixes #26 for others.

**Pull request merged**
