### PR TITLE
Support running tests ('behave features/') on OS X.

### PR DESCRIPTION
**Pull request by aanand**
Rebased + updated version of #43 - thanks, @j-bennet!

### CODE REVIEW

**Comment by dnephin** [comment]
LGTM

**Comment by aanand** [comment]
This will break #48 again if merged, and @TomasTomecek has already had to rebase a lot, so I'll hold off and rebase this once that's in.

**Comment by TomasTomecek** [comment]
(feel free to merge, it will be super-easy to rebase against this; I had a weak moment with [this](https://github.com/d11wtq/dockerpty/pull/48#issuecomment-173873466) comment)

**Comment by aanand** [comment]
@TomasTomecek OK, merged!

**Pull request merged**
