### PR TITLE
Make the logs argument to docker attach configurable

### LINKED ISSUE #51: Attaching to docker containers fails when specifying a log driver
I came here from https://github.com/docker/compose/issues/2448 since I'm bitten by the same issue. @glenbot [pointed out](https://github.com/docker/compose/issues/2448#issuecomment-161722916) that the problem is caused by [pty.py:188](https://github.com/d11wtq/dockerpty/blob/master/dockerpty/pty.py#L188) where the docker client is used to attach to the socket. Here dockerpty specifies `'logs': 1 ` which breaks when the container is running with a log driver.

Here's an example program that exercises the issue:

```python
import dockerpty
import docker
from docker.utils import kwargs_from_env

client = docker.Client(**kwargs_from_env())
container = client.create_container(
    image='busybox:latest',
    stdin_open=True,
    tty=True,
    command='/bin/sh',
    host_config={"LogConfig": {
        "Type": "none"
    }}
)

dockerpty.start(client, container['Id'], interactive=True)
```

I've verified that changing the value of logs to 0 makes the test program work as expected.

### PR DESCRIPTION
**Pull request by alf**
This pull request fixes #51 and is step 1 in fixing docker/compose#2448.

### CODE REVIEW

**Comment by aanand** [comment]
Thanks - see my note in https://github.com/d11wtq/dockerpty/issues/51#issuecomment-165778084 about showing a warning.

Not sure why CI is failing - it looks unrelated. Seems to be unable to find the `busybox:latest` image, even though we [pull it during setup](https://github.com/d11wtq/dockerpty/blob/7f0bb1510848f12b32c92ad25f9781b7268d6a9b/features/environment.py#L26).

**Comment by alf** [comment]
I'll add a deprecation warning about changing the default. I couldn't see why the tests failed either. I'll force push the deprecation warning in a few minutes.

**Comment by alf** [comment]
It seems that the build fails because the tests.sh script [can't find](https://travis-ci.org/d11wtq/dockerpty/jobs/97674585#L192) the `cgroups-mount` command.

**Comment by alf** [comment]
As far as I can understand, the most likely culprit is that the failing build runs on a different Linux Kernel.

From the last [working build](https://travis-ci.org/d11wtq/dockerpty/jobs/65955062#L13):

```
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04 LTS
Release:	12.04
Codename:	precise
Linux Version
2.6.32-042stab090.5
```

From my [failing build](https://travis-ci.org/d11wtq/dockerpty/jobs/97674585#L18):

```
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-63-generic
```

**Comment by alf** [comment]
By downloading the travis-ci log and looking at it properly I discovered that the apt-get install line in .travis.yml failed. :)

**Comment by alf** [comment]
```json
{
  "status": "Pulling repository busybox",
  "errorDetail": {"message":"Could not reach any registry endpoint"},
  "error": "Could not reach any registry endpoint"}
}

**Comment by alf** [comment]
Probable explanation: https://blog.docker.com/2015/10/docker-hub-deprecation-1-5/

**Comment by alf** [comment]
Unfortunately, it seems that busybox:latest has changed now that we're getting the image from docker-hub v2. Thus there is no /etc/issue and some of the feature tests break.

**Comment by dnephin** [comment]
There are test fixes in #48 that we need to get into master

**Comment by alf** [comment]
Ah, look at that. @TomasTomacek also found a much nicer fix for the build issues. :+1:

**Comment by alf** [comment]
@dnephin What's your preference? 

1. I can cherry pick the neccessary changes from #48 into this PR
2. I can cherry pick the build changes from #48 into a new PR that only does the build stuff
3. I can get rid of the build related changes in this PR and then rebase it later when someone else fixes the build

**Comment by dnephin** [comment]
Option 2 would be great

**Comment by alf** [comment]
Regarding the mystery test (watch), I suspect this could be an attempt to check whether watch is able to update the existing text instead of adding to the bottom of the screen. I won't bother fixing that now however.

**Comment by alf** [comment]
PR #53 fixes the build issues. I'll rebase this change on top of that.

**Comment by aanand** [comment]
Thanks for fixing the build! One typo, needs a rebase, then LGTM.

**Comment by alf** [comment]
Thanks. Rebased and fixed.

**Comment by dnephin** [comment]
LGTM

**Comment by TomasTomecek** [comment]
(would have split my PR if I saw this earlier, glad you solved it)

**Pull request merged**
