### PR TITLE
Unbreak the build

### PR DESCRIPTION
**Pull request by alf**

### CODE REVIEW

**Comment by alf** [comment]
Removed the Signed-off-by message since TomasTomacek didn't actually sign off on the ammended commit.

**Comment by alf** [comment]
Hat tip to @TomasTomecek for writing the code in this PR. Sorry if I overstepped my bounds by pulling it out into a separate PR.

**Comment by dnephin** [comment]
LGTM,

Thanks!

**Comment by aanand** [comment]
LGTM

**Pull request merged**
